/**
 * Il dizionario dell'analisi: le parole "chiuse" dell'inglese (pronomi,
 * articoli, preposizioni, congiunzioni, ausiliari, modali, avverbi), con la
 * loro categoria e i dettagli in italiano, e le classi di significato dei
 * nomi (tempo, luogo, persona, mezzo...) che servono a riconoscere i
 * complementi.
 *
 * compromise (la libreria che divide la frase e riconosce le parti del
 * discorso) sbaglia proprio su alcune di queste parole: per esempio prende
 * "who" per una preposizione. Qui la categoria è certa, e vince sempre.
 */

// ---------- Pronomi ----------

type InfoPronome = {
  tipo: string;
  persona?: 1 | 2 | 3;
  numero?: "singolare" | "plurale";
  // Il ruolo che il pronome può avere nella frase (I = soggetto, me = oggetto)
  caso?: "soggetto" | "complemento";
};

export const PRONOMI: Record<string, InfoPronome> = {
  i: {
    tipo: "personale soggetto",
    persona: 1,
    numero: "singolare",
    caso: "soggetto",
  },
  you: { tipo: "personale", persona: 2 },
  he: {
    tipo: "personale soggetto",
    persona: 3,
    numero: "singolare",
    caso: "soggetto",
  },
  she: {
    tipo: "personale soggetto",
    persona: 3,
    numero: "singolare",
    caso: "soggetto",
  },
  it: { tipo: "personale", persona: 3, numero: "singolare" },
  we: {
    tipo: "personale soggetto",
    persona: 1,
    numero: "plurale",
    caso: "soggetto",
  },
  they: {
    tipo: "personale soggetto",
    persona: 3,
    numero: "plurale",
    caso: "soggetto",
  },
  me: {
    tipo: "personale complemento",
    persona: 1,
    numero: "singolare",
    caso: "complemento",
  },
  him: {
    tipo: "personale complemento",
    persona: 3,
    numero: "singolare",
    caso: "complemento",
  },
  us: {
    tipo: "personale complemento",
    persona: 1,
    numero: "plurale",
    caso: "complemento",
  },
  them: {
    tipo: "personale complemento",
    persona: 3,
    numero: "plurale",
    caso: "complemento",
  },
  mine: { tipo: "possessivo", persona: 1, numero: "singolare" },
  yours: { tipo: "possessivo", persona: 2 },
  hers: { tipo: "possessivo", persona: 3, numero: "singolare" },
  ours: { tipo: "possessivo", persona: 1, numero: "plurale" },
  theirs: { tipo: "possessivo", persona: 3, numero: "plurale" },
  myself: { tipo: "riflessivo", persona: 1, numero: "singolare" },
  yourself: { tipo: "riflessivo", persona: 2, numero: "singolare" },
  himself: { tipo: "riflessivo", persona: 3, numero: "singolare" },
  herself: { tipo: "riflessivo", persona: 3, numero: "singolare" },
  itself: { tipo: "riflessivo", persona: 3, numero: "singolare" },
  ourselves: { tipo: "riflessivo", persona: 1, numero: "plurale" },
  yourselves: { tipo: "riflessivo", persona: 2, numero: "plurale" },
  themselves: { tipo: "riflessivo", persona: 3, numero: "plurale" },
  someone: { tipo: "indefinito", persona: 3, numero: "singolare" },
  somebody: { tipo: "indefinito", persona: 3, numero: "singolare" },
  something: { tipo: "indefinito", persona: 3, numero: "singolare" },
  anyone: { tipo: "indefinito", persona: 3, numero: "singolare" },
  anybody: { tipo: "indefinito", persona: 3, numero: "singolare" },
  anything: { tipo: "indefinito", persona: 3, numero: "singolare" },
  everyone: { tipo: "indefinito", persona: 3, numero: "singolare" },
  everybody: { tipo: "indefinito", persona: 3, numero: "singolare" },
  everything: { tipo: "indefinito", persona: 3, numero: "singolare" },
  nobody: { tipo: "indefinito negativo", persona: 3, numero: "singolare" },
  "no one": { tipo: "indefinito negativo", persona: 3, numero: "singolare" },
  nothing: { tipo: "indefinito negativo", persona: 3, numero: "singolare" },
  none: { tipo: "indefinito negativo", persona: 3 },
  who: { tipo: "interrogativo o relativo", persona: 3 },
  whom: { tipo: "interrogativo o relativo (complemento)", persona: 3 },
  whose: { tipo: "interrogativo o relativo (possesso)", persona: 3 },
  which: { tipo: "interrogativo o relativo", persona: 3 },
  what: { tipo: "interrogativo", persona: 3, numero: "singolare" },
  one: { tipo: "indefinito", persona: 3, numero: "singolare" },
};

// Aggettivi possessivi (vanno davanti al nome: my book)
export const POSSESSIVI: Record<string, string> = {
  my: "1ª persona singolare",
  your: "2ª persona",
  his: "3ª persona singolare maschile",
  her: "3ª persona singolare femminile",
  its: "3ª persona singolare (cosa o animale)",
  our: "1ª persona plurale",
  their: "3ª persona plurale",
};

// ---------- Articoli e determinanti ----------

export const ARTICOLI: Record<string, string> = {
  the: "articolo determinativo",
  a: "articolo indeterminativo",
  an: "articolo indeterminativo (davanti a vocale)",
};

// Dimostrativi, quantificatori e indefiniti che stanno davanti al nome
export const DETERMINANTI: Record<string, string> = {
  this: "aggettivo dimostrativo (vicino), singolare",
  that: "aggettivo dimostrativo (lontano), singolare",
  these: "aggettivo dimostrativo (vicino), plurale",
  those: "aggettivo dimostrativo (lontano), plurale",
  some: "aggettivo indefinito",
  any: "aggettivo indefinito",
  no: "aggettivo indefinito negativo",
  every: "aggettivo indefinito",
  each: "aggettivo indefinito",
  all: "aggettivo indefinito",
  both: "aggettivo indefinito",
  either: "aggettivo indefinito",
  neither: "aggettivo indefinito negativo",
  many: "aggettivo indefinito (quantità, numerabili)",
  much: "aggettivo indefinito (quantità, non numerabili)",
  few: "aggettivo indefinito (quantità)",
  little: "aggettivo indefinito (quantità)",
  several: "aggettivo indefinito (quantità)",
  more: "aggettivo indefinito (comparativo di quantità)",
  most: "aggettivo indefinito (superlativo di quantità)",
  less: "aggettivo indefinito (comparativo di quantità)",
  enough: "aggettivo indefinito (quantità)",
  another: "aggettivo indefinito",
  other: "aggettivo indefinito",
  such: "aggettivo indefinito",
  what: "aggettivo interrogativo",
  which: "aggettivo interrogativo",
  whose: "aggettivo interrogativo o relativo",
};

// ---------- Preposizioni ----------

export const PREPOSIZIONI = new Set([
  "about",
  "above",
  "across",
  "after",
  "against",
  "along",
  "among",
  "around",
  "as",
  "at",
  "before",
  "behind",
  "below",
  "beneath",
  "beside",
  "besides",
  "between",
  "beyond",
  "by",
  "despite",
  "down",
  "during",
  "except",
  "for",
  "from",
  "in",
  "inside",
  "into",
  "like",
  "near",
  "of",
  "off",
  "on",
  "onto",
  "opposite",
  "out",
  "outside",
  "over",
  "past",
  "per",
  "round",
  "since",
  "than",
  "through",
  "throughout",
  "till",
  "to",
  "toward",
  "towards",
  "under",
  "underneath",
  "unlike",
  "until",
  "up",
  "upon",
  "via",
  "with",
  "within",
  "without",
]);

// Preposizioni di più parole: si leggono come una sola
export const PREPOSIZIONI_COMPOSTE = [
  "because of",
  "in front of",
  "next to",
  "out of",
  "instead of",
  "thanks to",
  "according to",
  "in spite of",
  "close to",
  "far from",
  "on top of",
  "apart from",
  "due to",
  "in addition to",
  "as well as",
];

// ---------- Congiunzioni ----------

// Coordinanti: uniscono parti dello stesso tipo
export const CONGIUNZIONI_COORDINANTI: Record<string, string> = {
  and: "coordinante copulativa (aggiunge)",
  or: "coordinante disgiuntiva (alternativa)",
  but: "coordinante avversativa (contrapposizione)",
  so: "coordinante conclusiva (conseguenza)",
  yet: "coordinante avversativa",
  nor: "coordinante negativa",
};

// Subordinanti: introducono una proposizione dipendente, di cui dicono il tipo
export const CONGIUNZIONI_SUBORDINANTI: Record<
  string,
  { tipo: string; proposizione: string }
> = {
  because: { tipo: "subordinante causale", proposizione: "causale" },
  since: {
    tipo: "subordinante causale o temporale",
    proposizione: "causale o temporale",
  },
  as: {
    tipo: "subordinante causale o temporale",
    proposizione: "causale o temporale",
  },
  when: { tipo: "subordinante temporale", proposizione: "temporale" },
  whenever: { tipo: "subordinante temporale", proposizione: "temporale" },
  while: {
    tipo: "subordinante temporale (contemporaneità)",
    proposizione: "temporale",
  },
  before: {
    tipo: "subordinante temporale (anteriorità)",
    proposizione: "temporale",
  },
  after: {
    tipo: "subordinante temporale (posteriorità)",
    proposizione: "temporale",
  },
  until: {
    tipo: "subordinante temporale (fino a quando)",
    proposizione: "temporale",
  },
  till: {
    tipo: "subordinante temporale (fino a quando)",
    proposizione: "temporale",
  },
  "as soon as": {
    tipo: "subordinante temporale (non appena)",
    proposizione: "temporale",
  },
  if: {
    tipo: "subordinante ipotetica (condizionale)",
    proposizione: "ipotetica (condizionale)",
  },
  unless: {
    tipo: "subordinante ipotetica negativa (a meno che)",
    proposizione: "ipotetica (condizionale)",
  },
  although: { tipo: "subordinante concessiva", proposizione: "concessiva" },
  though: { tipo: "subordinante concessiva", proposizione: "concessiva" },
  "even though": {
    tipo: "subordinante concessiva",
    proposizione: "concessiva",
  },
  "even if": { tipo: "subordinante concessiva", proposizione: "concessiva" },
  whereas: { tipo: "subordinante avversativa", proposizione: "avversativa" },
  "so that": { tipo: "subordinante finale", proposizione: "finale" },
  "in order to": { tipo: "subordinante finale", proposizione: "finale" },
  that: {
    tipo: "subordinante dichiarativa",
    proposizione: "oggettiva (dichiarativa)",
  },
  whether: {
    tipo: "subordinante interrogativa indiretta",
    proposizione: "interrogativa indiretta",
  },
  where: {
    tipo: "avverbio relativo o interrogativo di luogo",
    proposizione: "relativa o di luogo",
  },
};

// Pronomi relativi indefiniti: introducono una relativa senza un nome a
// cui riferirsi (relativa libera): whatever it takes = qualunque cosa serva
export const RELATIVI_INDEFINITI: Record<string, string> = {
  whatever: "qualunque cosa, tutto ciò che",
  whoever: "chiunque",
  whomever: "chiunque (complemento)",
  whichever: "qualunque (tra più scelte)",
};

// Pronomi relativi: dopo un nome, introducono una proposizione relativa
export const RELATIVI = new Set([
  "who",
  "whom",
  "whose",
  "which",
  "that",
  "where",
]);

// Parole interrogative (domande aperte)
export const INTERROGATIVI: Record<string, string> = {
  what: "che cosa",
  who: "chi",
  whom: "chi (complemento)",
  whose: "di chi",
  which: "quale",
  where: "dove",
  when: "quando",
  why: "perché",
  how: "come",
};

// ---------- Verbi ausiliari e modali ----------

export const FORME_BE: Record<
  string,
  {
    tempo: "present" | "past" | "base" | "participle" | "ing";
    persona?: string;
  }
> = {
  am: { tempo: "present", persona: "1ª persona singolare" },
  is: { tempo: "present", persona: "3ª persona singolare" },
  are: { tempo: "present", persona: "2ª persona o plurale" },
  was: { tempo: "past", persona: "1ª o 3ª persona singolare" },
  were: { tempo: "past", persona: "2ª persona o plurale" },
  be: { tempo: "base" },
  been: { tempo: "participle" },
  being: { tempo: "ing" },
};

export const FORME_HAVE: Record<string, "present" | "past" | "base" | "ing"> = {
  have: "present",
  has: "present",
  had: "past",
  having: "ing",
};

export const FORME_DO: Record<string, "present" | "past"> = {
  do: "present",
  does: "present",
  did: "past",
};

// I modali, con i significati possibili (il contesto sceglie quello giusto)
export const MODALI: Record<
  string,
  { significati: string[]; lezione: string }
> = {
  will: {
    significati: [
      "futuro",
      "decisione presa ora",
      "promessa o offerta",
      "previsione",
    ],
    lezione: "lezione 28{1}",
  },
  would: {
    significati: ["condizionale", "richiesta gentile", "abitudine passata"],
    lezione: "lezione 36{1}",
  },
  shall: {
    significati: ["proposta o offerta (shall I/we...?)", "futuro (formale)"],
    lezione: "lezione 28{3}",
  },
  should: {
    significati: ["consiglio", "dovere morale", "probabilità"],
    lezione: "lezione 32{4}",
  },
  can: {
    significati: ["capacità", "permesso", "possibilità"],
    lezione: "lezione 25{1}",
  },
  could: {
    significati: ["capacità al passato", "richiesta gentile", "possibilità"],
    lezione: "lezione 25{5}",
  },
  may: {
    significati: ["possibilità", "permesso (formale)"],
    lezione: "lezione 28{5}",
  },
  might: { significati: ["possibilità remota"], lezione: "lezione 28{5}" },
  must: {
    significati: ["obbligo", "deduzione certa"],
    lezione: "lezione 32{1}",
  },
};

// Verbi copulativi: con un aggettivo o un nome formano il predicato nominale
export const COPULATIVI = new Set([
  "be",
  "seem",
  "become",
  "appear",
  "look",
  "feel",
  "sound",
  "taste",
  "smell",
  "remain",
  "stay",
  "get",
  "grow",
  "turn",
  "keep",
]);

// Verbi che reggono due complementi senza preposizione (give him a book)
export const DITRANSITIVI = new Set([
  "give",
  "send",
  "show",
  "tell",
  "buy",
  "bring",
  "offer",
  "teach",
  "lend",
  "pass",
  "write",
  "make",
  "cook",
  "get",
  "find",
  "pay",
  "sell",
  "read",
  "ask",
  "owe",
  "promise",
  "hand",
  "leave",
]);

// Verbi di movimento: con to/into indicano moto a luogo
export const MOVIMENTO = new Set([
  "go",
  "come",
  "move",
  "travel",
  "fly",
  "drive",
  "walk",
  "run",
  "return",
  "get",
  "arrive",
  "ride",
  "sail",
  "hurry",
  "rush",
  "climb",
  "jump",
  "fall",
  "send",
  "bring",
  "take",
  "carry",
]);

// Verbi dopo cui "that" introduce una frase (I think THAT he is right)
export const VERBI_DICHIARATIVI = new Set([
  "say",
  "think",
  "know",
  "believe",
  "hope",
  "tell",
  "hear",
  "feel",
  "realise",
  "realize",
  "mean",
  "show",
  "explain",
  "agree",
  "promise",
  "suggest",
  "guess",
  "suppose",
  "understand",
  "remember",
  "forget",
  "learn",
  "notice",
  "see",
  "doubt",
  "admit",
  "claim",
  "decide",
  "expect",
  "find",
  "imagine",
  "insist",
  "mention",
  "prove",
  "reply",
  "report",
  "be",
]);

// Participi usati quasi sempre come aggettivi dopo be (I'm tired)
export const PARTICIPI_AGGETTIVI = new Set([
  "tired",
  "exhausted",
  "bored",
  "interested",
  "excited",
  "surprised",
  "worried",
  "scared",
  "frightened",
  "married",
  "divorced",
  "closed",
  "amazed",
  "annoyed",
  "confused",
  "disappointed",
  "embarrassed",
  "pleased",
  "relaxed",
  "satisfied",
  "shocked",
  "stressed",
  "upset",
  "lost",
  "finished",
  "done",
  "dressed",
  "engaged",
  "located",
  "used",
]);

// Verbi di stato (non vanno al continuous)
export const VERBI_DI_STATO = new Set([
  "know",
  "believe",
  "understand",
  "remember",
  "forget",
  "mean",
  "like",
  "love",
  "hate",
  "prefer",
  "want",
  "need",
  "own",
  "belong",
  "seem",
  "contain",
  "consist",
  "depend",
  "deserve",
  "matter",
  "recognise",
  "recognize",
  "suppose",
  "realise",
  "realize",
  "wish",
]);

// ---------- Avverbi ----------

export const AVVERBI: Record<string, { tipo: string; complemento?: string }> = {
  // tempo
  now: { tipo: "di tempo", complemento: "tempo" },
  today: { tipo: "di tempo", complemento: "tempo" },
  tonight: { tipo: "di tempo", complemento: "tempo" },
  yesterday: { tipo: "di tempo", complemento: "tempo" },
  tomorrow: { tipo: "di tempo", complemento: "tempo" },
  then: { tipo: "di tempo", complemento: "tempo" },
  soon: { tipo: "di tempo", complemento: "tempo" },
  later: { tipo: "di tempo", complemento: "tempo" },
  early: { tipo: "di tempo", complemento: "tempo" },
  late: { tipo: "di tempo", complemento: "tempo" },
  already: { tipo: "di tempo", complemento: "tempo" },
  yet: { tipo: "di tempo", complemento: "tempo" },
  still: { tipo: "di tempo", complemento: "tempo" },
  just: { tipo: "di tempo (appena)", complemento: "tempo" },
  recently: { tipo: "di tempo", complemento: "tempo" },
  lately: { tipo: "di tempo", complemento: "tempo" },
  once: { tipo: "di tempo", complemento: "tempo" },
  ago: { tipo: "di tempo (fa)", complemento: "tempo" },
  before: { tipo: "di tempo", complemento: "tempo" },
  afterwards: { tipo: "di tempo", complemento: "tempo" },
  // frequenza
  always: { tipo: "di frequenza", complemento: "tempo (frequenza)" },
  usually: { tipo: "di frequenza", complemento: "tempo (frequenza)" },
  often: { tipo: "di frequenza", complemento: "tempo (frequenza)" },
  sometimes: { tipo: "di frequenza", complemento: "tempo (frequenza)" },
  rarely: { tipo: "di frequenza", complemento: "tempo (frequenza)" },
  seldom: { tipo: "di frequenza", complemento: "tempo (frequenza)" },
  never: { tipo: "di frequenza (negazione)", complemento: "tempo (frequenza)" },
  ever: {
    tipo: "di frequenza (mai, nelle domande)",
    complemento: "tempo (frequenza)",
  },
  occasionally: { tipo: "di frequenza", complemento: "tempo (frequenza)" },
  frequently: { tipo: "di frequenza", complemento: "tempo (frequenza)" },
  normally: { tipo: "di frequenza", complemento: "tempo (frequenza)" },
  // luogo
  here: { tipo: "di luogo", complemento: "luogo" },
  there: { tipo: "di luogo", complemento: "luogo" },
  home: { tipo: "di luogo", complemento: "luogo" },
  abroad: { tipo: "di luogo", complemento: "luogo" },
  everywhere: { tipo: "di luogo", complemento: "luogo" },
  somewhere: { tipo: "di luogo", complemento: "luogo" },
  anywhere: { tipo: "di luogo", complemento: "luogo" },
  nowhere: { tipo: "di luogo", complemento: "luogo" },
  upstairs: { tipo: "di luogo", complemento: "luogo" },
  downstairs: { tipo: "di luogo", complemento: "luogo" },
  outside: { tipo: "di luogo", complemento: "luogo" },
  inside: { tipo: "di luogo", complemento: "luogo" },
  away: { tipo: "di luogo", complemento: "luogo" },
  back: { tipo: "di luogo", complemento: "luogo" },
  // modo
  well: { tipo: "di modo", complemento: "modo" },
  badly: { tipo: "di modo", complemento: "modo" },
  fast: { tipo: "di modo", complemento: "modo" },
  hard: { tipo: "di modo", complemento: "modo" },
  together: { tipo: "di modo", complemento: "modo" },
  alone: { tipo: "di modo", complemento: "modo" },
  // quantità e grado (modificano un aggettivo o un avverbio)
  very: { tipo: "di quantità (grado)" },
  too: { tipo: "di quantità (troppo) o aggiuntivo (anche)" },
  quite: { tipo: "di quantità (grado)" },
  really: { tipo: "di quantità (grado)" },
  so: { tipo: "di quantità (grado)" },
  extremely: { tipo: "di quantità (grado)" },
  rather: { tipo: "di quantità (grado)" },
  pretty: { tipo: "di quantità (grado)" },
  almost: { tipo: "di quantità" },
  nearly: { tipo: "di quantità" },
  enough: { tipo: "di quantità" },
  more: { tipo: "di quantità (comparativo)" },
  most: { tipo: "di quantità (superlativo)" },
  less: { tipo: "di quantità (comparativo)" },
  // altri
  not: { tipo: "di negazione" },
  also: { tipo: "aggiuntivo (anche)" },
  only: { tipo: "limitativo (solo)" },
  even: { tipo: "aggiuntivo (perfino)" },
  maybe: { tipo: "di dubbio", complemento: "modo" },
  perhaps: { tipo: "di dubbio", complemento: "modo" },
  probably: { tipo: "di dubbio", complemento: "modo" },
  certainly: { tipo: "di affermazione", complemento: "modo" },
  definitely: { tipo: "di affermazione", complemento: "modo" },
  yes: { tipo: "di affermazione" },
  please: { tipo: "di cortesia" },
};

// Espressioni di tempo fatte da più parole senza preposizione
// (last week, next summer, every day, this morning, three years ago)
export const INIZIO_TEMPO = new Set(["last", "next", "every", "this", "each"]);

// Espressioni fisse che fanno da complemento senza preposizione
export const ESPRESSIONI: Record<string, string> = {
  "next door": "complemento di stato in luogo",
  "at home": "complemento di stato in luogo",
  "a lot": "complemento di quantità",
  "at once": "complemento di tempo determinato",
  "at last": "complemento di tempo determinato",
  "at first": "complemento di tempo determinato",
  "on time": "complemento di tempo determinato",
  "on foot": "complemento di mezzo",
  "by heart": "complemento di modo",
  "by chance": "complemento di modo",
  "on purpose": "complemento di modo",
  "in a hurry": "complemento di modo",
};

// ---------- Interiezioni ----------

export const INTERIEZIONI = new Set([
  "oh",
  "ah",
  "wow",
  "hey",
  "hi",
  "hello",
  "bye",
  "goodbye",
  "ouch",
  "oops",
  "hmm",
  "well",
  "yes",
  "no",
  "okay",
  "ok",
  "thanks",
  "cheers",
  "alas",
]);

// ---------- Classi di significato dei nomi ----------

export const NOMI_TEMPO = new Set([
  "time",
  "moment",
  "second",
  "minute",
  "hour",
  "day",
  "night",
  "morning",
  "afternoon",
  "evening",
  "week",
  "weekend",
  "month",
  "year",
  "decade",
  "century",
  "season",
  "spring",
  "summer",
  "autumn",
  "fall",
  "winter",
  "monday",
  "tuesday",
  "wednesday",
  "thursday",
  "friday",
  "saturday",
  "sunday",
  "january",
  "february",
  "march",
  "april",
  "may",
  "june",
  "july",
  "august",
  "september",
  "october",
  "november",
  "december",
  "christmas",
  "easter",
  "birthday",
  "holiday",
  "holidays",
  "past",
  "future",
  "o'clock",
  "noon",
  "midnight",
  "dawn",
  "sunset",
  "lunchtime",
  "breakfast",
  "lunch",
  "dinner",
  "childhood",
  "age",
  "period",
  "term",
  "semester",
  "while",
  "today",
  "tomorrow",
  "yesterday",
]);

export const NOMI_LUOGO = new Set([
  "home",
  "house",
  "flat",
  "apartment",
  "room",
  "kitchen",
  "bedroom",
  "bathroom",
  "garden",
  "office",
  "school",
  "university",
  "college",
  "class",
  "classroom",
  "library",
  "hospital",
  "church",
  "shop",
  "store",
  "supermarket",
  "market",
  "restaurant",
  "cafe",
  "café",
  "bar",
  "pub",
  "hotel",
  "station",
  "airport",
  "bank",
  "museum",
  "theatre",
  "theater",
  "cinema",
  "park",
  "street",
  "road",
  "square",
  "city",
  "town",
  "village",
  "country",
  "countryside",
  "world",
  "beach",
  "sea",
  "lake",
  "river",
  "mountain",
  "mountains",
  "forest",
  "island",
  "bed",
  "table",
  "desk",
  "sofa",
  "chair",
  "floor",
  "wall",
  "door",
  "window",
  "box",
  "bag",
  "car",
  "bus",
  "train",
  "plane",
  "corner",
  "centre",
  "center",
  "place",
  "area",
  "north",
  "south",
  "east",
  "west",
  "abroad",
  "gym",
  "pool",
  "stadium",
  "zoo",
  "farm",
  "field",
  "building",
  "hall",
  "lab",
  "laboratory",
  "capital",
  "kingdom",
  "england",
  "britain",
  "london",
  "oxford",
  "italy",
  "rome",
]);

// Mezzi di trasporto (by bus, by car...)
export const NOMI_MEZZO = new Set([
  "bus",
  "car",
  "train",
  "plane",
  "bike",
  "bicycle",
  "taxi",
  "boat",
  "ship",
  "foot",
  "underground",
  "tube",
  "metro",
  "coach",
  "motorbike",
  "air",
  "sea",
  "email",
  "phone",
  "post",
  "mail",
  "hand",
]);

// Strumenti (with a knife, with a pen...)
export const NOMI_STRUMENTO = new Set([
  "pen",
  "pencil",
  "knife",
  "fork",
  "spoon",
  "key",
  "hammer",
  "phone",
  "computer",
  "laptop",
  "camera",
  "brush",
  "scissors",
  "stick",
  "tool",
  "machine",
  "help",
  "hands",
  "hand",
  "glass",
  "cup",
]);

// Nomi astratti che con "with" indicano il modo (with care, with joy)
export const NOMI_MODO = new Set([
  "care",
  "attention",
  "patience",
  "pleasure",
  "joy",
  "love",
  "difficulty",
  "ease",
  "interest",
  "enthusiasm",
  "passion",
  "fear",
  "anger",
  "pride",
  "respect",
  "kindness",
  "success",
  "confidence",
]);

// Nomi di persona (oltre a quelli che compromise già riconosce)
export const NOMI_PERSONA = new Set([
  "friend",
  "friends",
  "mother",
  "father",
  "mum",
  "mom",
  "dad",
  "parent",
  "parents",
  "brother",
  "sister",
  "son",
  "daughter",
  "child",
  "children",
  "kid",
  "baby",
  "boy",
  "girl",
  "man",
  "woman",
  "men",
  "women",
  "people",
  "person",
  "teacher",
  "student",
  "doctor",
  "nurse",
  "boss",
  "colleague",
  "neighbour",
  "neighbor",
  "wife",
  "husband",
  "boyfriend",
  "girlfriend",
  "partner",
  "family",
  "grandmother",
  "grandfather",
  "grandparents",
  "aunt",
  "uncle",
  "cousin",
  "author",
  "writer",
  "king",
  "queen",
  "police",
  "everyone",
  "everybody",
  "someone",
  "somebody",
  "nobody",
  "team",
  "guest",
  "customer",
  "waiter",
  "tutor",
  "classmate",
]);
